# Generated by Django 4.1.7 on 2023-10-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="is_staff",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="is_superuser",
            field=models.BooleanField(default=True),
        ),
    ]
