# Generated by Django 4.1.7 on 2023-05-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
