# Generated by Django 4.1.7 on 2023-04-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="slug",
            field=models.SlugField(blank=True, max_length=150, verbose_name="slug"),
        ),
    ]
