# Generated by Django 4.1.7 on 2023-04-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="avatar",
            field=models.CharField(max_length=2048),
        ),
    ]
