# Generated by Django 4.1.7 on 2023-06-29 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0002_alter_account_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={},
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="created_datetime",
            new_name="created_date",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="updated_datetime",
            new_name="modified_date",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="comment_text",
            new_name="text",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="level",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="lft",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="replies_count",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="report_reasons",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="rght",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="status",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="tree_id",
        ),
        migrations.AlterField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="journal_api.comment",
            ),
        ),
        migrations.AlterModelTable(
            name="comment",
            table=None,
        ),
    ]
