# Generated by Django 4.1.7 on 2023-04-17 14:17

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0002_alter_post_publish_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="publish_datetime",
            field=models.DateTimeField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.datetime(2023, 4, 17, 17, 22, 23, 696095)
                    )
                ],
            ),
        ),
    ]
