# Generated by Django 4.1.7 on 2023-06-29 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0003_alter_comment_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"verbose_name": "Comment", "verbose_name_plural": "Comment"},
        ),
    ]
