# Generated by Django 4.1.7 on 2023-06-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0004_alter_comment_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ["-created_datetime"],
                "verbose_name": "Comment",
                "verbose_name_plural": "Comment",
            },
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="created_date",
            new_name="created_datetime",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="modified_date",
            new_name="updated_datetime",
        ),
        migrations.AddField(
            model_name="comment",
            name="replies_count",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="comment",
            name="report_reasons",
            field=models.ManyToManyField(
                blank=True,
                through="journal_api.CommentReport",
                to="journal_api.reportreason",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="status",
            field=models.CharField(
                choices=[("n", "normal"), ("b", "banned"), ("d", "deleted")],
                default="n",
                max_length=5,
            ),
        ),
        migrations.AlterModelTable(
            name="comment",
            table="Comment",
        ),
    ]
