# Generated by Django 4.1.7 on 2023-10-25 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0004_rename_date_created_subscription_subscribtion_datetime"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="subscribtion_datetime",
            new_name="subscription_datetime",
        ),
    ]
