# Generated by Django 4.1.7 on 2023-04-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0005_alter_post_publish_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="publish_datetime",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
