# Generated by Django 4.1.7 on 2023-10-26 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "journal_api",
            "0005_rename_subscribtion_datetime_subscription_subscription_datetime",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="postreaction",
            name="author",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
