# Generated by Django 4.1.7 on 2023-06-29 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0005_alter_comment_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="comments_count",
        ),
    ]
