# Generated by Django 4.1.7 on 2023-06-29 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0006_remove_post_comments_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="favorites_reaction",
        ),
        migrations.RemoveField(
            model_name="account",
            name="recent_reaction",
        ),
        migrations.RemoveField(
            model_name="post",
            name="reactions",
        ),
        migrations.RemoveField(
            model_name="postreaction",
            name="reaction",
        ),
        migrations.AddField(
            model_name="postreaction",
            name="reaction_type",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="postreaction",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="journal_api.post",
            ),
        ),
        migrations.DeleteModel(
            name="Reaction",
        ),
        migrations.DeleteModel(
            name="ReactionCategory",
        ),
    ]
