# Generated by Django 4.1.7 on 2023-12-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0007_alter_account_managers_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ["-created_datetime"],
                "verbose_name": "Notification",
                "verbose_name_plural": "Notification",
            },
        ),
        migrations.AddField(
            model_name="account",
            name="about_info",
            field=models.BooleanField(blank=True, max_length=200, null=True),
        ),
    ]
