# Generated by Django 4.1.7 on 2023-04-17 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0007_alter_post_publish_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="publish_datetime",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
