# Generated by Django 4.1.7 on 2023-07-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0007_remove_account_favorites_reaction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="num_comments",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="postreaction",
            name="reaction_type",
            field=models.CharField(
                choices=[("like", "Like"), ("dislike", "Dislike")],
                max_length=10,
                null=True,
            ),
        ),
    ]
