# Generated by Django 4.1.7 on 2023-07-04 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0008_comment_num_comments_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="num_comments",
        ),
    ]
