# Generated by Django 4.1.7 on 2023-12-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0008_alter_notification_options_account_about_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="about_info",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
