# Generated by Django 4.1.7 on 2023-12-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0009_alter_account_about_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/user_avatars/%Y/%m/%d/"
            ),
        ),
    ]
