# Generated by Django 4.1.7 on 2023-04-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0009_alter_post_is_publish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="publish_datetime",
            field=models.DateTimeField(blank=True),
        ),
    ]
