# Generated by Django 4.1.7 on 2023-07-08 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0010_alter_comment_author_alter_post_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentreaction",
            name="comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_reactions",
                to="journal_api.comment",
            ),
        ),
        migrations.AlterField(
            model_name="postreaction",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_reactions",
                to="journal_api.post",
            ),
        ),
    ]
