# Generated by Django 4.1.7 on 2023-12-14 16:09

from django.db import migrations, models
import journal_api.models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0010_alter_account_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=journal_api.models.avatar_upload_to
            ),
        ),
    ]
