# Generated by Django 4.1.7 on 2023-07-10 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0011_alter_commentreaction_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="num_comments",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="postreaction",
            name="author",
            field=models.ForeignKey(
                blank=True,
                default="user doesn't exist",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="postreaction",
            name="reaction_type",
            field=models.CharField(
                blank=True,
                choices=[("like", "Like"), ("dislike", "Dislike")],
                max_length=10,
                null=True,
            ),
        ),
    ]
