# Generated by Django 4.1.7 on 2023-12-25 14:49

from django.db import migrations, models
import journal_api.models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0011_alter_account_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="background_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=journal_api.models.background_image__upload_to,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="profile_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="tagname",
            field=models.CharField(
                blank=True, db_index=True, max_length=150, null=True
            ),
        ),
    ]
