# Generated by Django 4.1.7 on 2024-01-10 14:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0012_account_background_image_account_profile_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="all_stats",
            field=models.CharField(
                blank=True,
                choices=[
                    ("post_likes", "post_dislikes"),
                    ("comment_likes", "comment_dislikes"),
                    ("comment_reply", "comment_reply"),
                    ("posts_count", "comments_count"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="selected_stats",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
