# Generated by Django 4.1.7 on 2023-07-10 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0012_post_num_comments_alter_postreaction_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                blank=True,
                default="user doesn't exist",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("n", "normal"), ("b", "banned"), ("d", "deleted")],
                default="n",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(blank=True),
        ),
    ]
