# Generated by Django 4.1.7 on 2024-01-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0013_account_all_stats_account_selected_stats"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="all_stats",
        ),
        migrations.RemoveField(
            model_name="account",
            name="selected_stats",
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(blank=True, max_length=75, null=True),
        ),
    ]
