# Generated by Django 4.1.7 on 2023-07-10 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0013_alter_comment_author_alter_comment_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="journal_api.comment",
            ),
        ),
        migrations.AlterField(
            model_name="postreaction",
            name="author",
            field=models.ForeignKey(
                default="user doesn't exist",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
