# Generated by Django 4.1.7 on 2024-01-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0013_account_all_stats_account_selected_stats"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option_name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(max_length=75, null=True, unique=True)),
            ],
            options={
                "verbose_name": "Stats",
                "verbose_name_plural": "Stats",
                "db_table": "Stats",
            },
        ),
        migrations.RemoveField(
            model_name="account",
            name="all_stats",
        ),
        migrations.RemoveField(
            model_name="account",
            name="selected_stats",
        ),
        migrations.AddField(
            model_name="account",
            name="stats",
            field=models.ManyToManyField(blank=True, to="journal_api.stats"),
        ),
    ]
