# Generated by Django 4.1.7 on 2024-01-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0014_stats_remove_account_all_stats_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stats",
            name="slug",
            field=models.SlugField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(max_length=75, null=True),
        ),
    ]
