# Generated by Django 4.1.7 on 2023-07-10 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0014_alter_comment_parent_alter_postreaction_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                default="user doesn't exist",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="journal_api.comment",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="status",
            field=models.CharField(
                choices=[("n", "normal"), ("b", "banned"), ("d", "deleted")],
                default="n",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="postreaction",
            name="reaction_type",
            field=models.CharField(
                choices=[("like", "Like"), ("dislike", "Dislike")],
                max_length=10,
                null=True,
            ),
        ),
    ]
