# Generated by Django 4.1.7 on 2024-01-12 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0014_stats_remove_account_all_stats_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option_name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=75, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Stats",
                "verbose_name_plural": "Stats",
                "db_table": "Stats",
            },
        ),
        migrations.CreateModel(
            name="AccountStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="journal_api.stats",
                    ),
                ),
            ],
            options={
                "verbose_name": "Account Stats",
                "verbose_name_plural": "Account Stats",
                "db_table": "AccountStats",
            },
        ),
        migrations.AddField(
            model_name="account",
            name="stats",
            field=models.ManyToManyField(
                blank=True, through="journal_api.AccountStats", to="journal_api.stats"
            ),
        ),
    ]
