# Generated by Django 4.1.7 on 2023-07-10 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0015_alter_comment_author_alter_comment_parent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="num_comments",
        ),
    ]
