# Generated by Django 4.1.7 on 2024-01-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0015_alter_stats_slug_alter_tag_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stats",
            name="slug",
            field=models.SlugField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(blank=True, max_length=75, null=True),
        ),
    ]
