# Generated by Django 4.1.7 on 2024-01-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0015_stats_accountstats_account_stats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stats",
            name="order",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
