# Generated by Django 4.1.7 on 2023-04-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0015_alter_post_is_publish"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="thumbnail",
            field=models.URLField(blank=True, null=True),
        ),
    ]
