# Generated by Django 4.1.7 on 2024-01-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0016_alter_stats_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stats",
            name="order",
        ),
        migrations.AddField(
            model_name="accountstats",
            name="order",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
