# Generated by Django 4.1.7 on 2023-04-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0016_post_thumbnail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="date_created",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="created_date",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="updated_date",
        ),
        migrations.RemoveField(
            model_name="post",
            name="created_date",
        ),
        migrations.RemoveField(
            model_name="post",
            name="updated_date",
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(max_length=75, null=True, unique=True),
        ),
    ]
