# Generated by Django 4.1.7 on 2023-07-10 15:41

from django.db import migrations, models
import django.db.models.aggregates


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0017_post_num_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="num_comments",
            field=models.IntegerField(
                blank=True, default=django.db.models.aggregates.Count("comments")
            ),
        ),
    ]
