# Generated by Django 4.1.7 on 2024-01-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0017_remove_stats_order_accountstats_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="stats",
            field=models.ManyToManyField(
                blank=True,
                related_name="AccountStats",
                through="journal_api.AccountStats",
                to="journal_api.stats",
            ),
        ),
    ]
