# Generated by Django 4.1.7 on 2023-07-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0018_alter_post_num_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="num_comments",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
