# Generated by Django 4.1.7 on 2023-07-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0019_alter_post_num_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="activation_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="is_activated",
            field=models.BooleanField(default=False),
        ),
    ]
