# Generated by Django 4.1.7 on 2023-07-18 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0020_account_activation_code_account_is_activated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="is_activated",
        ),
    ]
