# Generated by Django 4.1.7 on 2023-07-18 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0021_remove_account_is_activated"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="activation_code",
            new_name="confirmation_code",
        ),
    ]
