# Generated by Django 4.1.7 on 2023-07-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0022_rename_activation_code_account_confirmation_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
