# Generated by Django 4.1.7 on 2023-07-22 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0023_alter_account_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="journal_api.post",
            ),
        ),
        migrations.AlterField(
            model_name="postreaction",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_reactions",
                to="journal_api.post",
            ),
        ),
    ]
