# Generated by Django 4.1.7 on 2023-07-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0024_alter_comment_post_alter_postreaction_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postreaction",
            name="reaction_type",
            field=models.CharField(
                blank=True,
                choices=[("like", "Like"), ("dislike", "Dislike")],
                max_length=10,
                null=True,
            ),
        ),
    ]
