# Generated by Django 4.1.7 on 2023-08-12 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0025_alter_postreaction_reaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                default='',
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="journal_api.post",
            ),
            preserve_default=False,
        ),
    ]
