# Generated by Django 4.1.7 on 2023-08-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0026_alter_comment_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.CharField(max_length=500),
        ),
    ]
