# Generated by Django 4.1.7 on 2023-08-17 13:36

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0027_alter_post_body_alter_post_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=tinymce.models.HTMLField(),
        ),
    ]
