# Generated by Django 4.1.7 on 2023-08-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0028_alter_post_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
