# Generated by Django 4.1.7 on 2023-08-28 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0029_alter_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="avatar",
            field=models.ImageField(
                blank=True, upload_to="media/images/user_avatars/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/images/post_thumbnail/%Y/%m/%d/"
            ),
        ),
        migrations.CreateModel(
            name="PostBodyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="media/images/post_body/%Y/%m/%d/"
                    ),
                ),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="journal_api.post",
                    ),
                ),
            ],
            options={
                "verbose_name": "PostBodyImage",
                "verbose_name_plural": "PostBodyImage",
                "db_table": "PostBodyImage",
                "ordering": ["-created_datetime"],
            },
        ),
    ]
