# Generated by Django 4.1.7 on 2023-08-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0030_alter_account_avatar_alter_post_thumbnail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_draft",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="post",
            name="is_publish",
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
