# Generated by Django 4.1.7 on 2023-08-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0031_post_is_draft_alter_post_is_publish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="avatar",
            field=models.ImageField(
                blank=True, upload_to="images/user_avatars/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/post_thumbnail/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="postbodyimage",
            name="image",
            field=models.ImageField(blank=True, upload_to="images/post_body/%Y/%m/%d/"),
        ),
    ]
