# Generated by Django 4.1.7 on 2023-09-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0032_alter_account_avatar_alter_post_thumbnail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="allow_comments",
            field=models.BooleanField(default=True),
        ),
    ]
