# Generated by Django 4.1.7 on 2023-10-03 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0034_subscription_alter_commentreaction_comment_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="subscriber",
            new_name="user",
        ),
    ]
