# Generated by Django 4.1.7 on 2023-10-03 15:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0035_rename_subscriber_subscription_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="subscribed_to",
            field=models.ManyToManyField(
                blank=True, related_name="subscribers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
