# Generated by Django 4.1.7 on 2023-10-21 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0036_alter_subscription_subscribed_to"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("seen_datetime", models.DateTimeField(blank=True, null=True)),
                ("seen", models.BooleanField(default=False)),
                (
                    "notification_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("post_reaction", "Leave reaction to your post"),
                            ("post_comment", "Leave comment to your post"),
                            ("comment_reply", "Create reply to your comment"),
                            ("comment_reaction", "Leave reaction to your comment"),
                            ("subscribe", "User subscribe to you"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("notification_data", models.JSONField()),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
