# Generated by Django 4.1.7 on 2023-10-21 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0037_notification"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notification",
            },
        ),
        migrations.RemoveField(
            model_name="notification",
            name="notification_data",
        ),
        migrations.AddField(
            model_name="notification",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_notifications",
                to="journal_api.comment",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="comment_reaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_reaction_notifications",
                to="journal_api.commentreaction",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_notifications",
                to="journal_api.post",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="post_reaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_reaction_notifications",
                to="journal_api.postreaction",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="subscribe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscribe_notifications",
                to="journal_api.subscription",
            ),
        ),
        migrations.AlterModelTable(
            name="notification",
            table="Notification",
        ),
    ]
