# Generated by Django 4.1.7 on 2023-10-21 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0038_alter_notification_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="subscribe",
        ),
        migrations.AddField(
            model_name="notification",
            name="subscriber",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriber_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("post_reaction", "Leave reaction to your post"),
                    ("post_comment", "Leave comment to your post"),
                    ("comment_reply", "Create reply to your comment"),
                    ("comment_reaction", "Leave reaction to your comment"),
                    ("subscribe", "User subscribe to you"),
                ],
                max_length=50,
            ),
        ),
    ]
