# Generated by Django 4.1.7 on 2023-10-21 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0039_remove_notification_subscribe_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("post_reaction", "post_reaction"),
                    ("post_comment", "post_comment"),
                    ("comment_reply", "comment_reply"),
                    ("comment_reaction", "comment_reaction"),
                    ("subscribe", "subscribe"),
                ],
                max_length=50,
            ),
        ),
    ]
