# Generated by Django 4.1.7 on 2023-10-21 15:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal_api", "0041_subscription_subscriptionrelationship_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="subscriber",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="subscription",
            name="subscribed_to",
            field=models.ManyToManyField(
                blank=True, related_name="subscribers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
